module.exports = {
  'strict-ui-boundary': require('./strict-ui-boundary'),
  'fsd-strict-boundaries': require('./fsd-strict-boundaries'),
  'fsd-no-banned-segments': require('./fsd-no-banned-segments'),
  'fsd-no-deep-import': require('./fsd-no-deep-import'),
  'fsd-layer-direction': require('./fsd-layer-direction'),
  'fsd-no-driver-outside-repository': require('./fsd-no-driver-outside-repository'),
  'interaction-hover-needs-focus': require('./interaction-hover-needs-focus'),
  'interaction-pattern-contract': require('./interaction-pattern-contract'),
  'no-action-in-state': require('./no-action-in-state'),
  'no-arbitrary-sleep-in-tests': require('./no-arbitrary-sleep-in-tests'),
  'no-boolean-state-flags': require('./no-boolean-state-flags'),
  'no-complex-ternary': require('./no-complex-ternary'),
  'no-derived-state-member': require('./no-derived-state-member'),
  'no-fetch-in-component': require('./no-fetch-in-component'),
  'no-nondeterministic-render': require('./no-nondeterministic-render'),
  'no-refetch-in-effect': require('./no-refetch-in-effect'),
  'no-response-type-assertion': require('./no-response-type-assertion'),
  'no-swallowed-rejection': require('./no-swallowed-rejection'),
  'no-use-client-above-leaf': require('./no-use-client-above-leaf'),
  'require-abort-signal-passthrough': require('./require-abort-signal-passthrough'),
  'require-discriminated-state': require('./require-discriminated-state'),
  'require-effect-annotation': require('./require-effect-annotation'),
  'require-exact-call-count': require('./require-exact-call-count'),
  'require-skip-reason': require('./require-skip-reason'),
  'scenario-test-filename': require('./scenario-test-filename'),
}
