/* eslint-disable global-require */
module.exports = {
  'fsd-no-banned-segments': require('./fsd-no-banned-segments'),
  'fsd-no-deep-import': require('./fsd-no-deep-import'),
  'fsd-no-driver-outside-repository': require('./fsd-no-driver-outside-repository'),
  'no-arbitrary-sleep-in-tests': require('./no-arbitrary-sleep-in-tests'),
  'no-boolean-state-flags': require('./no-boolean-state-flags'),
  'no-complex-ternary': require('./no-complex-ternary'),
  'no-console-log': require('./no-console-log'),
  'no-css-locator-without-reason': require('./no-css-locator-without-reason'),
  'no-derived-state-effect': require('./no-derived-state-effect'),
  'no-fetch-in-component': require('./no-fetch-in-component'),
  'no-refetch-in-effect': require('./no-refetch-in-effect'),
  'no-response-type-assertion': require('./no-response-type-assertion'),
  'no-use-client-above-leaf': require('./no-use-client-above-leaf'),
  'require-abort-signal-passthrough': require('./require-abort-signal-passthrough'),
  'require-discriminated-state': require('./require-discriminated-state'),
  'require-effect-annotation': require('./require-effect-annotation'),
  'require-exact-call-count': require('./require-exact-call-count'),
  'require-skip-reason': require('./require-skip-reason'),
  'scenario-test-filename': require('./scenario-test-filename'),
}
